version: "3"
services:
    grafana:
        image: "grafana/grafana"
        restart: always
        networks:
          - loggernet
        ports:
          - "3000:3000"

    influx:
        image: "influxdb"
        restart: always
        networks:
          - loggernet
        ports:
          - "8086:8086"
        volumes:
          - ./influxdb-data:/var/lib/influxdb

networks:
  loggernet: