version: "3"
services:
    # Grafana container docs: http://docs.grafana.org/installation/docker/
    grafana:
        image: "grafana/grafana"
        restart: always
        networks:
          - loggernet
        ports:
          - "3000:3000"
        volumes:
          - ./grafana-storage-data:/var/lib/grafana 
        # Para futura configuração AD/LDAP: http://docs.grafana.org/auth/ldap/
        env_file:
          - ./env/grafana-variables.env

    influx:
        image: "influxdb"
        restart: always
        networks:
          - loggernet
        ports:
          - "8086:8086"
        volumes:
          - ./influxdb-data:/var/lib/influxdb

networks:
  loggernet: