{
 "title": "Dashboard enContact",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Administradores/Dashboard conectados",
   "type": "singlestat",
   "description": "Conexões de administradores e dashboards.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\n  COUNT(*) as value,\n  'logged_agent' as metric\nFROM\n  sessions with(nolock)\nWHERE\n  Type != 1\n  and\n  end_date IS NULL"
    }
   ]
  },
  {
   "title": "Operadores conectados",
   "type": "singlestat",
   "description": "Quantidade de sessões ativas de operadores.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\n  COUNT(*) as value,\n  'logged_agent' as metric\nFROM\n  sessions with(nolock)\nWHERE\n  Type = 1\n  and\n  end_date IS NULL"
    }
   ]
  },
  {
   "title": "Emails Recebidos/Enviados",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "Quantidade" }
   ],
   "targets": [
    {
     "rawSql": "With cte As\n(\n\tSELECT \n\t\tDateAdd(minute, 5 * (DateDiff(minute, '20000101', download_date) / 5), '20000101') As ReceivedDate,\n\t\t1 as Item\n\tFROM received_emails with(nolock)\n\tWHERE\n\t\t$__timeFilter(download_date)\n)\nSelect \n  DATEDIFF(second, '1970-01-01', ReceivedDate) AS time,\n  SUM(Item) As Value,\n  'Recebidos' as metric\nFrom cte\nGroup By ReceivedDate\nOrder By ReceivedDate\n"
    },
    {
     "rawSql": "\nWith cte As\n(\n\tSELECT \n\t\tDateAdd(minute, 5 * (DateDiff(minute, '20000101', RegisterDate) / 5), '20000101') As RegisterDate,\n\t\t1 as Item\n\tFROM sent_emails with(nolock)\n\tWHERE\n\t\t$__timeFilter(RegisterDate)\n\t\tand\n\t\twas_sent = 1\n)\nSelect \n  DATEDIFF(second, '1970-01-01', RegisterDate) AS time,\n  SUM(Item) As Value,\n  'Envios confirmados' as metric\nFrom cte\nGroup By RegisterDate\nOrder By RegisterDate"
    },
    {
     "rawSql": "\nWith cte As\n(\n\tSELECT \n\t\tDateAdd(minute, 5 * (DateDiff(minute, '20000101', RegisterDate) / 5), '20000101') As RegisterDate,\n\t\t1 as Item\n\tFROM sent_emails with(nolock)\n\tWHERE\n\t\t$__timeFilter(RegisterDate)\n\t\tand\n\t\twas_sent = 0\n)\nSelect \n  DATEDIFF(second, '1970-01-01', RegisterDate) AS time,\n  SUM(Item) As Value,\n  'Envios pendentes/falhos' as metric\nFrom cte\nGroup By RegisterDate\nOrder By RegisterDate"
    }
   ]
  },
  {
   "title": "Logs no período",
   "type": "graph",
   "description": "Apresenta um gráfico com a quantidade de logs gerados num determinado período.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "locale", "label": "Quantidade" }
   ],
   "targets": [
    {
     "rawSql": "With cte As\n(\n\tSELECT \n\t\tDateAdd(minute, 5 * (DateDiff(minute, '20000101', Date) / 5), '20000101') As LogDate,\n\t\t1 as Item\n\tFROM log with(nolock)\n\tWHERE\n\t\t$__timeFilter(Date)\n)\nSelect \n  DATEDIFF(second, '1970-01-01', LogDate) AS time,\n  SUM(Item) As Value,\n  'Quantidade Total' as metric\nFrom cte\nGroup By LogDate\nOrder By LogDate"
    },
    {
     "rawSql": "With cte As\n(\n\tSELECT \n\t\tDateAdd(minute, 5 * (DateDiff(minute, '20000101', Date) / 5), '20000101') As LogDate,\n\t\t1 as Item\n\tFROM log with(nolock)\n\tWHERE\n\t\t$__timeFilter(Date)\n\t\tAND\n\t\tLevel = 'ERROR'\n)\nSelect \n  DATEDIFF(second, '1970-01-01', LogDate) AS time,\n  SUM(Item) As Value,\n  'Total Erros' as metric\nFrom cte\nGroup By LogDate\nOrder By LogDate"
    },
    {
     "rawSql": "With cte As\n(\n\tSELECT \n\t\tDateAdd(minute, 5 * (DateDiff(minute, '20000101', Date) / 5), '20000101') As LogDate,\n\t\t1 as Item\n\tFROM log with(nolock)\n\tWHERE\n\t\t$__timeFilter(Date)\n\t\tAND\n\t\tLevel = 'WARN'\n)\nSelect \n  DATEDIFF(second, '1970-01-01', LogDate) AS time,\n  SUM(Item) As Value,\n  'Total Warns' as metric\nFrom cte\nGroup By LogDate\nOrder By LogDate"
    }
   ]
  },
  {
   "title": "Apresentação inconsistências detectadas",
   "type": "table",
   "description": "Apresenta todas as inconsistências detectadas no sistema que precisem ser ajustadas manualmente.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select c.ClientId, cl.NickName as ClientName, c.Id as ContactId, e.Id as EmailId, c.UserId as ContactUser, e.UserId as EmailUser, e.Date as EmailDate, 'UPDATE Contact SET UserId = 0 WHERE Id = ' + CAST(ContactId as nvarchar) as 'Update Command' from Contact c with(nolock) inner join emails e with(nolock) on e.ContactId = c.Id and c.EmailId = e.Id inner join client cl with(nolock) on cl.Id = c.ClientId where c.Status = 4 and e.Status = 2 and e.UserId != c.UserId and cl.Active = 1"
    }
   ]
  }
 ]
}